Question.create([
    {question_text: "Organization"},
    {question_text: "Application Contact", closed_question: false},
    {question_text: "Title", closed_question: false},
    {question_text: "Phone", closed_question: false},
    {question_text: "Email", closed_question: false},
    {question_text: "Address", closed_question: false},
    {question_text: "Proposed Participant", closed_question: false},
    {question_text: "Title", closed_question: false},
    {question_text: "Phone", closed_question: false},
    {question_text: "Email", closed_question: false},
    {question_text: "Date Organized", closed_question: false},
    {question_text: "Number of Full-Time Employees", closed_question: false},
    {question_text: "Number of Part-Time Employees", closed_question: false},
    {question_text: "Budget for current fiscal", closed_question: false},
    {question_text: "What are your current sources of funding (include percentages)?", closed_question: false},
    {question_text: "Do you have your 501c3?", closed_question: true},
    {question_text: "If not, do you have a fiscal agent?", closed_question: true},
    {question_text: "Name of fiscal agent (if applicable)", closed_question: false},
    {question_text: "Briefly describe what your organization does (Limit 300 words)", closed_question: false},
    {question_text: "What communities do you serve?", closed_question: false},
    {question_text: "Who do you help (target population)?", closed_question: false},
    {question_text: "How does your nonprofit make a meaningful impact (Limit 200 words)", closed_question: false},
    {question_text: "How do you measure the impact of your nonprofit? Please share any relevant statistics.", closed_question: false},
    {question_text: "What differentiates you from other organizations working to address the same issues? (Limit 300 words)", closed_question: false},
    {question_text: "What are your organization's goals for the coming year (Limit 300 words)", closed_question: false},
    {question_text: "What do you hope to gain from participating in Fast Pitch? (Limit 100 words)", closed_question: false},
    {question_text: "What is the one thing you most want us to know about your organization (Limit 200 words)", closed_question: false}])
Sector.create([
    {name: "Alcoholism, Addiction"},
    {name: "Education"},
    {name: "Elderly Care"},
    {name: "Food"},
    {name: "Health, Medical"},
    {name: "Homelessness"},
    {name: "Job Programs"},
    {name: "Mental Health"},
    {name: "Pregnancy, Parenting"},
    {name: "Violence, Abuse"},
    {name: "Other"}
  ])
